"""Jira tools for Atlassian integration.

This module provides type-safe functions for interacting with Jira,
including issue management, search, projects, sprints, and more.
"""

from atlassian_tools.jira.tools import (
    jira_add_comment,
    jira_add_watcher,
    jira_add_worklog,
    jira_assign_issue,
    jira_batch_create_issues,
    jira_create_issue,
    jira_delete_comment,
    jira_delete_issue,
    jira_get_all_projects,
    jira_get_board_issues,
    jira_get_comments,
    jira_get_epic_issues,
    jira_get_fields,
    jira_get_issue,
    jira_get_link_types,
    jira_get_priorities,
    jira_get_project_issues,
    jira_get_resolutions,
    jira_get_sprint_issues,
    jira_get_transitions,
    jira_get_user_profile,
    jira_get_watchers,
    jira_get_worklog,
    jira_link_issues,
    jira_remove_watcher,
    jira_search,
    jira_transition_issue,
    jira_unlink_issues,
    jira_update_comment,
    jira_update_issue,
)

__all__ = [
    "jira_add_comment",
    "jira_add_watcher",
    "jira_add_worklog",
    "jira_assign_issue",
    "jira_batch_create_issues",
    "jira_create_issue",
    "jira_delete_comment",
    "jira_delete_issue",
    "jira_get_all_projects",
    "jira_get_board_issues",
    "jira_get_comments",
    "jira_get_epic_issues",
    "jira_get_fields",
    "jira_get_issue",
    "jira_get_link_types",
    "jira_get_priorities",
    "jira_get_project_issues",
    "jira_get_resolutions",
    "jira_get_sprint_issues",
    "jira_get_transitions",
    "jira_get_user_profile",
    "jira_get_watchers",
    "jira_get_worklog",
    "jira_link_issues",
    "jira_remove_watcher",
    "jira_search",
    "jira_transition_issue",
    "jira_unlink_issues",
    "jira_update_comment",
    "jira_update_issue",
]
